### ISSUE TITLE
Fixed code for adding multiple languages to Metadata

### ISSUE THREAD

**Issue by ianweatherburn** [dvnlgls/GM-IMDb-Page-Cleaner#2]
Some releases have mutliple languages, so I updated the code to add all of the language(s) metadata under the release title. In addition, I included the original CSS styling to the new language metadata to fit with the original.
I've created the new function (below) `addLanguageMetadata()` for this, which obviously needs to be called from somewhere (such as `modifyLayout()` probably being the best place?)

```javascript
function addLanguageMetadata() {
  const languages = document.querySelectorAll(".ipc-metadata-list [data-testid='title-details-languages'] .ipc-inline-list__item .ipc-metadata-list-item__list-content-item--link");
  const titleMetadata = document.querySelectorAll(".ipc-inline-list.ipc-inline-list--show-dividers.sc-afe43def-4.kdXikI.baseAlt")[0];

  if (languages && titleMetadata) {
      languages.forEach(language => {
          const languageElement = document.createElement("li");
          languageElement.textContent = language.textContent;
          languageElement.setAttribute("role", "presentation");
          languageElement.classList.add("ipc-inline-list__item");
          titleMetadata.appendChild(languageElement);
      });
  }
}
```
The result for multiple languages, now appears like this for example:
![Major](https://github.com/dvnlgls/GM-IMDb-Page-Cleaner/assets/19514284/12c0869e-8bf5-4fa0-bf6f-6a85a91a29a9)

**Comment by dvnlgls** [comment]
Good catch! Before publishing your code, I'd like to make a suggestion. I feel relying on class name to get language & titleMetadata is prone to breaking since they might update the class names anytime. I propose relying on "data-testid" attribute and inherent html structure which are less likely to change. For instance, I quickly tested the following way on multiple pages successfully:

```
const languages = [...document.querySelectorAll("[data-testid='title-details-languages'] a")];

const titleParent = document.querySelector("[data-testid='hero__pageTitle']").parentNode; // thought it's a little safer to use the parent instead of sibling
const titleMetadata = titleParent.getElementsByTagName('ul')[0] ;
```

BTW, since you're interested in IMDb, might I show you something I built a while ago? Please check out https://theshowgrid.com/ You might find it useful.

**Comment by ianweatherburn** [comment]
That is much better. Thank you. I'm still learning about the DOM but this makes sense, and it does appear to be fractionally quicker. I can confirm the following code. therefore appears to be working. Thanks again.
Re. ShowGrid - cool website. Thank you.

```Javascript
function addLanguageMetadata() {
  const languages = [...document.querySelectorAll("[data-testid='title-details-languages'] a")];
  const titleParent = document.querySelector("[data-testid='hero__pageTitle']").parentNode; 
  const titleMetadata = titleParent.getElementsByTagName('ul')[0] ;

  if (languages && titleMetadata) {
      languages.forEach(language => {
          const languageElement = document.createElement("li");
          languageElement.textContent = language.textContent;
          languageElement.setAttribute("role", "presentation");
          languageElement.classList.add("ipc-inline-list__item");
          titleMetadata.appendChild(languageElement);
      });
  }
}
```

**Comment by dvnlgls** [comment]
You're welcome. Published the updated code, thanks.
